// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vision.proto

package com.example.ex3_2_back.grpc.server.vision;

public interface FaceCollectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vision.FaceCollectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>string identity = 2;</code>
   * @return The identity.
   */
  java.lang.String getIdentity();
  /**
   * <code>string identity = 2;</code>
   * @return The bytes for identity.
   */
  com.google.protobuf.ByteString
      getIdentityBytes();

  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   *算法从该地址拉流
   * </pre>
   *
   * <code>string pull_url = 4;</code>
   * @return The pullUrl.
   */
  java.lang.String getPullUrl();
  /**
   * <pre>
   *算法从该地址拉流
   * </pre>
   *
   * <code>string pull_url = 4;</code>
   * @return The bytes for pullUrl.
   */
  com.google.protobuf.ByteString
      getPullUrlBytes();

  /**
   * <pre>
   * 算法向该地址推流
   * </pre>
   *
   * <code>string push_url = 5;</code>
   * @return The pushUrl.
   */
  java.lang.String getPushUrl();
  /**
   * <pre>
   * 算法向该地址推流
   * </pre>
   *
   * <code>string push_url = 5;</code>
   * @return The bytes for pushUrl.
   */
  com.google.protobuf.ByteString
      getPushUrlBytes();
}
