// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vision.proto

package com.example.ex3_2_back.grpc.server.vision;

/**
 * <pre>
 * model_id: 1-人脸识别 2-摔倒检测 3-入侵检测
 * </pre>
 *
 * Protobuf type {@code vision.StartVisonServiceRequest}
 */
public final class StartVisonServiceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vision.StartVisonServiceRequest)
    StartVisonServiceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StartVisonServiceRequest.newBuilder() to construct.
  private StartVisonServiceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StartVisonServiceRequest() {
    pullUrl_ = "";
    pushUrl_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StartVisonServiceRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.ex3_2_back.grpc.server.vision.VisionProto.internal_static_vision_StartVisonServiceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.ex3_2_back.grpc.server.vision.VisionProto.internal_static_vision_StartVisonServiceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest.class, com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest.Builder.class);
  }

  public static final int CAMERA_ID_FIELD_NUMBER = 1;
  private int cameraId_ = 0;
  /**
   * <code>int32 camera_id = 1;</code>
   * @return The cameraId.
   */
  @java.lang.Override
  public int getCameraId() {
    return cameraId_;
  }

  public static final int PULL_URL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pullUrl_ = "";
  /**
   * <pre>
   *算法从该地址拉流
   * </pre>
   *
   * <code>string pull_url = 2;</code>
   * @return The pullUrl.
   */
  @java.lang.Override
  public java.lang.String getPullUrl() {
    java.lang.Object ref = pullUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pullUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *算法从该地址拉流
   * </pre>
   *
   * <code>string pull_url = 2;</code>
   * @return The bytes for pullUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPullUrlBytes() {
    java.lang.Object ref = pullUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pullUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUSH_URL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pushUrl_ = "";
  /**
   * <pre>
   * 算法向该地址推流
   * </pre>
   *
   * <code>string push_url = 3;</code>
   * @return The pushUrl.
   */
  @java.lang.Override
  public java.lang.String getPushUrl() {
    java.lang.Object ref = pushUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pushUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 算法向该地址推流
   * </pre>
   *
   * <code>string push_url = 3;</code>
   * @return The bytes for pushUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPushUrlBytes() {
    java.lang.Object ref = pushUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pushUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_ID_FIELD_NUMBER = 4;
  private int modelId_ = 0;
  /**
   * <code>int32 model_id = 4;</code>
   * @return The modelId.
   */
  @java.lang.Override
  public int getModelId() {
    return modelId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cameraId_ != 0) {
      output.writeInt32(1, cameraId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pullUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pullUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pushUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pushUrl_);
    }
    if (modelId_ != 0) {
      output.writeInt32(4, modelId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cameraId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, cameraId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pullUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pullUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pushUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pushUrl_);
    }
    if (modelId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, modelId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest)) {
      return super.equals(obj);
    }
    com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest other = (com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest) obj;

    if (getCameraId()
        != other.getCameraId()) return false;
    if (!getPullUrl()
        .equals(other.getPullUrl())) return false;
    if (!getPushUrl()
        .equals(other.getPushUrl())) return false;
    if (getModelId()
        != other.getModelId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CAMERA_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCameraId();
    hash = (37 * hash) + PULL_URL_FIELD_NUMBER;
    hash = (53 * hash) + getPullUrl().hashCode();
    hash = (37 * hash) + PUSH_URL_FIELD_NUMBER;
    hash = (53 * hash) + getPushUrl().hashCode();
    hash = (37 * hash) + MODEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getModelId();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * model_id: 1-人脸识别 2-摔倒检测 3-入侵检测
   * </pre>
   *
   * Protobuf type {@code vision.StartVisonServiceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vision.StartVisonServiceRequest)
      com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.ex3_2_back.grpc.server.vision.VisionProto.internal_static_vision_StartVisonServiceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.ex3_2_back.grpc.server.vision.VisionProto.internal_static_vision_StartVisonServiceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest.class, com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest.Builder.class);
    }

    // Construct using com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cameraId_ = 0;
      pullUrl_ = "";
      pushUrl_ = "";
      modelId_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.ex3_2_back.grpc.server.vision.VisionProto.internal_static_vision_StartVisonServiceRequest_descriptor;
    }

    @java.lang.Override
    public com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest getDefaultInstanceForType() {
      return com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest build() {
      com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest buildPartial() {
      com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest result = new com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cameraId_ = cameraId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pullUrl_ = pullUrl_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pushUrl_ = pushUrl_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.modelId_ = modelId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest) {
        return mergeFrom((com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest other) {
      if (other == com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest.getDefaultInstance()) return this;
      if (other.getCameraId() != 0) {
        setCameraId(other.getCameraId());
      }
      if (!other.getPullUrl().isEmpty()) {
        pullUrl_ = other.pullUrl_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPushUrl().isEmpty()) {
        pushUrl_ = other.pushUrl_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getModelId() != 0) {
        setModelId(other.getModelId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              cameraId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              pullUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              pushUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              modelId_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int cameraId_ ;
    /**
     * <code>int32 camera_id = 1;</code>
     * @return The cameraId.
     */
    @java.lang.Override
    public int getCameraId() {
      return cameraId_;
    }
    /**
     * <code>int32 camera_id = 1;</code>
     * @param value The cameraId to set.
     * @return This builder for chaining.
     */
    public Builder setCameraId(int value) {

      cameraId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 camera_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCameraId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cameraId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object pullUrl_ = "";
    /**
     * <pre>
     *算法从该地址拉流
     * </pre>
     *
     * <code>string pull_url = 2;</code>
     * @return The pullUrl.
     */
    public java.lang.String getPullUrl() {
      java.lang.Object ref = pullUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pullUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *算法从该地址拉流
     * </pre>
     *
     * <code>string pull_url = 2;</code>
     * @return The bytes for pullUrl.
     */
    public com.google.protobuf.ByteString
        getPullUrlBytes() {
      java.lang.Object ref = pullUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pullUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *算法从该地址拉流
     * </pre>
     *
     * <code>string pull_url = 2;</code>
     * @param value The pullUrl to set.
     * @return This builder for chaining.
     */
    public Builder setPullUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pullUrl_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *算法从该地址拉流
     * </pre>
     *
     * <code>string pull_url = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPullUrl() {
      pullUrl_ = getDefaultInstance().getPullUrl();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *算法从该地址拉流
     * </pre>
     *
     * <code>string pull_url = 2;</code>
     * @param value The bytes for pullUrl to set.
     * @return This builder for chaining.
     */
    public Builder setPullUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pullUrl_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object pushUrl_ = "";
    /**
     * <pre>
     * 算法向该地址推流
     * </pre>
     *
     * <code>string push_url = 3;</code>
     * @return The pushUrl.
     */
    public java.lang.String getPushUrl() {
      java.lang.Object ref = pushUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pushUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 算法向该地址推流
     * </pre>
     *
     * <code>string push_url = 3;</code>
     * @return The bytes for pushUrl.
     */
    public com.google.protobuf.ByteString
        getPushUrlBytes() {
      java.lang.Object ref = pushUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pushUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 算法向该地址推流
     * </pre>
     *
     * <code>string push_url = 3;</code>
     * @param value The pushUrl to set.
     * @return This builder for chaining.
     */
    public Builder setPushUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pushUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算法向该地址推流
     * </pre>
     *
     * <code>string push_url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPushUrl() {
      pushUrl_ = getDefaultInstance().getPushUrl();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算法向该地址推流
     * </pre>
     *
     * <code>string push_url = 3;</code>
     * @param value The bytes for pushUrl to set.
     * @return This builder for chaining.
     */
    public Builder setPushUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pushUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int modelId_ ;
    /**
     * <code>int32 model_id = 4;</code>
     * @return The modelId.
     */
    @java.lang.Override
    public int getModelId() {
      return modelId_;
    }
    /**
     * <code>int32 model_id = 4;</code>
     * @param value The modelId to set.
     * @return This builder for chaining.
     */
    public Builder setModelId(int value) {

      modelId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 model_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      modelId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vision.StartVisonServiceRequest)
  }

  // @@protoc_insertion_point(class_scope:vision.StartVisonServiceRequest)
  private static final com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest();
  }

  public static com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StartVisonServiceRequest>
      PARSER = new com.google.protobuf.AbstractParser<StartVisonServiceRequest>() {
    @java.lang.Override
    public StartVisonServiceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StartVisonServiceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StartVisonServiceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

