// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vision.proto

package com.example.ex3_2_back.grpc.server.vision;

public interface StartVisonServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vision.StartVisonServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 camera_id = 1;</code>
   * @return The cameraId.
   */
  int getCameraId();

  /**
   * <pre>
   *算法从该地址拉流
   * </pre>
   *
   * <code>string pull_url = 2;</code>
   * @return The pullUrl.
   */
  java.lang.String getPullUrl();
  /**
   * <pre>
   *算法从该地址拉流
   * </pre>
   *
   * <code>string pull_url = 2;</code>
   * @return The bytes for pullUrl.
   */
  com.google.protobuf.ByteString
      getPullUrlBytes();

  /**
   * <pre>
   * 算法向该地址推流
   * </pre>
   *
   * <code>string push_url = 3;</code>
   * @return The pushUrl.
   */
  java.lang.String getPushUrl();
  /**
   * <pre>
   * 算法向该地址推流
   * </pre>
   *
   * <code>string push_url = 3;</code>
   * @return The bytes for pushUrl.
   */
  com.google.protobuf.ByteString
      getPushUrlBytes();

  /**
   * <code>int32 model_id = 4;</code>
   * @return The modelId.
   */
  int getModelId();
}
