// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vision.proto

package com.example.ex3_2_back.grpc.server.vision;

/**
 * Protobuf service {@code vision.VisionService}
 */
public  abstract class VisionService
    implements com.google.protobuf.Service {
  protected VisionService() {}

  public interface Interface {
    /**
     * <code>rpc FaceCollection(.vision.FaceCollectionRequest) returns (.vision.CommonResopnse);</code>
     */
    public abstract void faceCollection(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.vision.FaceCollectionRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.vision.CommonResopnse> done);

    /**
     * <code>rpc RemoveUrl(.vision.RemoveUrlRequest) returns (.vision.CommonResopnse);</code>
     */
    public abstract void removeUrl(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.vision.RemoveUrlRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.vision.CommonResopnse> done);

    /**
     * <code>rpc StartVisonService(.vision.StartVisonServiceRequest) returns (.vision.CommonResopnse);</code>
     */
    public abstract void startVisonService(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.vision.CommonResopnse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new VisionService() {
      @java.lang.Override
      public  void faceCollection(
          com.google.protobuf.RpcController controller,
          com.example.ex3_2_back.grpc.server.vision.FaceCollectionRequest request,
          com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.vision.CommonResopnse> done) {
        impl.faceCollection(controller, request, done);
      }

      @java.lang.Override
      public  void removeUrl(
          com.google.protobuf.RpcController controller,
          com.example.ex3_2_back.grpc.server.vision.RemoveUrlRequest request,
          com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.vision.CommonResopnse> done) {
        impl.removeUrl(controller, request, done);
      }

      @java.lang.Override
      public  void startVisonService(
          com.google.protobuf.RpcController controller,
          com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest request,
          com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.vision.CommonResopnse> done) {
        impl.startVisonService(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.faceCollection(controller, (com.example.ex3_2_back.grpc.server.vision.FaceCollectionRequest)request);
          case 1:
            return impl.removeUrl(controller, (com.example.ex3_2_back.grpc.server.vision.RemoveUrlRequest)request);
          case 2:
            return impl.startVisonService(controller, (com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.ex3_2_back.grpc.server.vision.FaceCollectionRequest.getDefaultInstance();
          case 1:
            return com.example.ex3_2_back.grpc.server.vision.RemoveUrlRequest.getDefaultInstance();
          case 2:
            return com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance();
          case 1:
            return com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance();
          case 2:
            return com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc FaceCollection(.vision.FaceCollectionRequest) returns (.vision.CommonResopnse);</code>
   */
  public abstract void faceCollection(
      com.google.protobuf.RpcController controller,
      com.example.ex3_2_back.grpc.server.vision.FaceCollectionRequest request,
      com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.vision.CommonResopnse> done);

  /**
   * <code>rpc RemoveUrl(.vision.RemoveUrlRequest) returns (.vision.CommonResopnse);</code>
   */
  public abstract void removeUrl(
      com.google.protobuf.RpcController controller,
      com.example.ex3_2_back.grpc.server.vision.RemoveUrlRequest request,
      com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.vision.CommonResopnse> done);

  /**
   * <code>rpc StartVisonService(.vision.StartVisonServiceRequest) returns (.vision.CommonResopnse);</code>
   */
  public abstract void startVisonService(
      com.google.protobuf.RpcController controller,
      com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest request,
      com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.vision.CommonResopnse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.example.ex3_2_back.grpc.server.vision.VisionProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.faceCollection(controller, (com.example.ex3_2_back.grpc.server.vision.FaceCollectionRequest)request,
          com.google.protobuf.RpcUtil.<com.example.ex3_2_back.grpc.server.vision.CommonResopnse>specializeCallback(
            done));
        return;
      case 1:
        this.removeUrl(controller, (com.example.ex3_2_back.grpc.server.vision.RemoveUrlRequest)request,
          com.google.protobuf.RpcUtil.<com.example.ex3_2_back.grpc.server.vision.CommonResopnse>specializeCallback(
            done));
        return;
      case 2:
        this.startVisonService(controller, (com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest)request,
          com.google.protobuf.RpcUtil.<com.example.ex3_2_back.grpc.server.vision.CommonResopnse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.ex3_2_back.grpc.server.vision.FaceCollectionRequest.getDefaultInstance();
      case 1:
        return com.example.ex3_2_back.grpc.server.vision.RemoveUrlRequest.getDefaultInstance();
      case 2:
        return com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance();
      case 1:
        return com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance();
      case 2:
        return com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.example.ex3_2_back.grpc.server.vision.VisionService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void faceCollection(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.vision.FaceCollectionRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.vision.CommonResopnse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.ex3_2_back.grpc.server.vision.CommonResopnse.class,
          com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance()));
    }

    public  void removeUrl(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.vision.RemoveUrlRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.vision.CommonResopnse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.ex3_2_back.grpc.server.vision.CommonResopnse.class,
          com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance()));
    }

    public  void startVisonService(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.vision.CommonResopnse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.ex3_2_back.grpc.server.vision.CommonResopnse.class,
          com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.example.ex3_2_back.grpc.server.vision.CommonResopnse faceCollection(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.vision.FaceCollectionRequest request)
        throws com.google.protobuf.ServiceException;

    public com.example.ex3_2_back.grpc.server.vision.CommonResopnse removeUrl(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.vision.RemoveUrlRequest request)
        throws com.google.protobuf.ServiceException;

    public com.example.ex3_2_back.grpc.server.vision.CommonResopnse startVisonService(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.example.ex3_2_back.grpc.server.vision.CommonResopnse faceCollection(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.vision.FaceCollectionRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.ex3_2_back.grpc.server.vision.CommonResopnse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance());
    }


    public com.example.ex3_2_back.grpc.server.vision.CommonResopnse removeUrl(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.vision.RemoveUrlRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.ex3_2_back.grpc.server.vision.CommonResopnse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance());
    }


    public com.example.ex3_2_back.grpc.server.vision.CommonResopnse startVisonService(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.vision.StartVisonServiceRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.ex3_2_back.grpc.server.vision.CommonResopnse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.vision.CommonResopnse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:vision.VisionService)
}

