#需要修改配置
server:
  port: 8080

grpc:
  server:
    port: 9999
    inProcessName: test
client:
  event-service:
    address: host.docker.internal:9090
    negotiationType: plaintext
  message-service:
    address: host.docker.internal:8503
#    address: localhost:8503
#    address: 8.130.169.249:8503
#    address: 172.20.10.6:8503
    negotiationType: plaintext

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform:
  datasource:
    url: jdbc:mysql://c_mysql:3306/nursing_home?serverTimezone=GMT%2B8
    password: "123456789"
    username: root

oss:
  endpoint: "oss-cn-beijing.aliyuncs.com"
  access-key-id: "LTAI5tGuLnH1EvkEG6XhbZqG"
  access-key-secret: "izeXdapmAcAseHyUaLfOVNHKFLrRWP"
  bucket-name: "hyxzjbnb"

logging:
  level:
    root: info  # 根日志级别设置为info，将会记录info及以上级别的日志
#    com.example.ex3_2_back: debug  # 指定某个包的日志级别为debug
#    org.hibernate.SQL: trace
#    org:
#      hibernate:
#        orm:
#          jdbc:
#            bind: trace
  file:
    name: app.log   # 指定日志文件名称
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"   # 指定控制台输出的日志格式
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"   # 指定日志文件输出的日志格式
  appenders:
    file:
      type: file
      fileName: ${logging.file.name}
      append: true
    console:
      type: console
