#需要修改配置
server:
  port: 8080

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse_test?serverTimezone=GMT%2B8
    password: ""
    username: root

springfox:
  documentation:
    swagger-ui:
      enabled: false

logging:
  level:
    root: info   # 根日志级别设置为info，将会记录info及以上级别的日志
  file:
    name: app.log   # 指定日志文件名称
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"   # 指定控制台输出的日志格式
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"   # 指定日志文件输出的日志格式
  appenders:
    file:
      type: file
      fileName: ${logging.file.name}
      append: true
    console:
      type: console

dataInit: false