// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.example.ex3_2_back.grpc.server.event;

public interface EmotionDetectionEventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event.EmotionDetectionEventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 elderlyId = 1;</code>
   * @return The elderlyId.
   */
  int getElderlyId();

  /**
   * <code>string imageUrl = 2;</code>
   * @return The imageUrl.
   */
  java.lang.String getImageUrl();
  /**
   * <code>string imageUrl = 2;</code>
   * @return The bytes for imageUrl.
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();

  /**
   * <code>string emotion = 3;</code>
   * @return The emotion.
   */
  java.lang.String getEmotion();
  /**
   * <code>string emotion = 3;</code>
   * @return The bytes for emotion.
   */
  com.google.protobuf.ByteString
      getEmotionBytes();

  /**
   * <code>int32 cameraId = 4;</code>
   * @return The cameraId.
   */
  int getCameraId();
}
