// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.example.ex3_2_back.grpc.server.event;

public final class EventServiceProto {
  private EventServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_EventServerResopnse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_EventServerResopnse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_EmotionDetectionEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_EmotionDetectionEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_VolunteerInteractionEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_VolunteerInteractionEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_StrangerDetectionEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_StrangerDetectionEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_FallDetectionEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_FallDetectionEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_ForbiddenAreaInvasionDetectionEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_ForbiddenAreaInvasionDetectionEventRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\005event\"B\n\023EventServerResop" +
      "nse\022\017\n\007message\030\001 \001(\t\022\014\n\004code\030\002 \001(\005\022\014\n\004da" +
      "ta\030\003 \001(\t\"C\n\034EmotionDetectionEventRequest" +
      "\022\021\n\telderlyId\030\001 \001(\005\022\020\n\010imageUrl\030\002 \001(\t\"\\\n" +
      " VolunteerInteractionEventRequest\022\021\n\teld" +
      "erlyId\030\001 \001(\005\022\023\n\013volunteerId\030\002 \001(\005\022\020\n\010ima" +
      "geUrl\030\003 \001(\t\"1\n\035StrangerDetectionEventReq" +
      "uest\022\020\n\010imageUrl\030\001 \001(\t\"-\n\031FallDetectionE" +
      "ventRequest\022\020\n\010imageUrl\030\001 \001(\t\">\n*Forbidd" +
      "enAreaInvasionDetectionEventRequest\022\020\n\010i" +
      "mageUrl\030\001 \001(\t2\360\003\n\014EventService\022X\n\025Emotio" +
      "nDetectionEvent\022#.event.EmotionDetection" +
      "EventRequest\032\032.event.EventServerResopnse" +
      "\022`\n\031VolunteerInteractionEvent\022\'.event.Vo" +
      "lunteerInteractionEventRequest\032\032.event.E" +
      "ventServerResopnse\022Z\n\026StrangerDetectionE" +
      "vent\022$.event.StrangerDetectionEventReque" +
      "st\032\032.event.EventServerResopnse\022R\n\022FallDe" +
      "tectionEvent\022 .event.FallDetectionEventR" +
      "equest\032\032.event.EventServerResopnse\022t\n#Fo" +
      "rbiddenAreaInvasionDetectionEvent\0221.even" +
      "t.ForbiddenAreaInvasionDetectionEventReq" +
      "uest\032\032.event.EventServerResopnseBB\n(com." +
      "example.ex3_2_back.grpc.server.eventB\021Ev" +
      "entServiceProtoP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_event_EventServerResopnse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_EventServerResopnse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_EventServerResopnse_descriptor,
        new java.lang.String[] { "Message", "Code", "Data", });
    internal_static_event_EmotionDetectionEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_event_EmotionDetectionEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_EmotionDetectionEventRequest_descriptor,
        new java.lang.String[] { "ElderlyId", "ImageUrl", });
    internal_static_event_VolunteerInteractionEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_event_VolunteerInteractionEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_VolunteerInteractionEventRequest_descriptor,
        new java.lang.String[] { "ElderlyId", "VolunteerId", "ImageUrl", });
    internal_static_event_StrangerDetectionEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_event_StrangerDetectionEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_StrangerDetectionEventRequest_descriptor,
        new java.lang.String[] { "ImageUrl", });
    internal_static_event_FallDetectionEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_event_FallDetectionEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_FallDetectionEventRequest_descriptor,
        new java.lang.String[] { "ImageUrl", });
    internal_static_event_ForbiddenAreaInvasionDetectionEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_event_ForbiddenAreaInvasionDetectionEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_ForbiddenAreaInvasionDetectionEventRequest_descriptor,
        new java.lang.String[] { "ImageUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
