// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.example.ex3_2_back.grpc.server.event;

/**
 * Protobuf service {@code event.EventService}
 */
public  abstract class EventService
    implements com.google.protobuf.Service {
  protected EventService() {}

  public interface Interface {
    /**
     * <pre>
     *    rpc CreateEvent(EventRequest) returns (EventServerResopnse);
     * </pre>
     *
     * <code>rpc EmotionDetectionEvent(.event.EmotionDetectionEventRequest) returns (.event.EventServerResopnse);</code>
     */
    public abstract void emotionDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.EmotionDetectionEventRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done);

    /**
     * <code>rpc VolunteerInteractionEvent(.event.VolunteerInteractionEventRequest) returns (.event.EventServerResopnse);</code>
     */
    public abstract void volunteerInteractionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.VolunteerInteractionEventRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done);

    /**
     * <code>rpc StrangerDetectionEvent(.event.StrangerDetectionEventRequest) returns (.event.EventServerResopnse);</code>
     */
    public abstract void strangerDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.StrangerDetectionEventRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done);

    /**
     * <code>rpc FallDetectionEvent(.event.FallDetectionEventRequest) returns (.event.EventServerResopnse);</code>
     */
    public abstract void fallDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.FallDetectionEventRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done);

    /**
     * <code>rpc ForbiddenAreaInvasionDetectionEvent(.event.ForbiddenAreaInvasionDetectionEventRequest) returns (.event.EventServerResopnse);</code>
     */
    public abstract void forbiddenAreaInvasionDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.ForbiddenAreaInvasionDetectionEventRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new EventService() {
      @java.lang.Override
      public  void emotionDetectionEvent(
          com.google.protobuf.RpcController controller,
          com.example.ex3_2_back.grpc.server.event.EmotionDetectionEventRequest request,
          com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done) {
        impl.emotionDetectionEvent(controller, request, done);
      }

      @java.lang.Override
      public  void volunteerInteractionEvent(
          com.google.protobuf.RpcController controller,
          com.example.ex3_2_back.grpc.server.event.VolunteerInteractionEventRequest request,
          com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done) {
        impl.volunteerInteractionEvent(controller, request, done);
      }

      @java.lang.Override
      public  void strangerDetectionEvent(
          com.google.protobuf.RpcController controller,
          com.example.ex3_2_back.grpc.server.event.StrangerDetectionEventRequest request,
          com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done) {
        impl.strangerDetectionEvent(controller, request, done);
      }

      @java.lang.Override
      public  void fallDetectionEvent(
          com.google.protobuf.RpcController controller,
          com.example.ex3_2_back.grpc.server.event.FallDetectionEventRequest request,
          com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done) {
        impl.fallDetectionEvent(controller, request, done);
      }

      @java.lang.Override
      public  void forbiddenAreaInvasionDetectionEvent(
          com.google.protobuf.RpcController controller,
          com.example.ex3_2_back.grpc.server.event.ForbiddenAreaInvasionDetectionEventRequest request,
          com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done) {
        impl.forbiddenAreaInvasionDetectionEvent(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.emotionDetectionEvent(controller, (com.example.ex3_2_back.grpc.server.event.EmotionDetectionEventRequest)request);
          case 1:
            return impl.volunteerInteractionEvent(controller, (com.example.ex3_2_back.grpc.server.event.VolunteerInteractionEventRequest)request);
          case 2:
            return impl.strangerDetectionEvent(controller, (com.example.ex3_2_back.grpc.server.event.StrangerDetectionEventRequest)request);
          case 3:
            return impl.fallDetectionEvent(controller, (com.example.ex3_2_back.grpc.server.event.FallDetectionEventRequest)request);
          case 4:
            return impl.forbiddenAreaInvasionDetectionEvent(controller, (com.example.ex3_2_back.grpc.server.event.ForbiddenAreaInvasionDetectionEventRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.ex3_2_back.grpc.server.event.EmotionDetectionEventRequest.getDefaultInstance();
          case 1:
            return com.example.ex3_2_back.grpc.server.event.VolunteerInteractionEventRequest.getDefaultInstance();
          case 2:
            return com.example.ex3_2_back.grpc.server.event.StrangerDetectionEventRequest.getDefaultInstance();
          case 3:
            return com.example.ex3_2_back.grpc.server.event.FallDetectionEventRequest.getDefaultInstance();
          case 4:
            return com.example.ex3_2_back.grpc.server.event.ForbiddenAreaInvasionDetectionEventRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance();
          case 1:
            return com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance();
          case 2:
            return com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance();
          case 3:
            return com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance();
          case 4:
            return com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   *    rpc CreateEvent(EventRequest) returns (EventServerResopnse);
   * </pre>
   *
   * <code>rpc EmotionDetectionEvent(.event.EmotionDetectionEventRequest) returns (.event.EventServerResopnse);</code>
   */
  public abstract void emotionDetectionEvent(
      com.google.protobuf.RpcController controller,
      com.example.ex3_2_back.grpc.server.event.EmotionDetectionEventRequest request,
      com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done);

  /**
   * <code>rpc VolunteerInteractionEvent(.event.VolunteerInteractionEventRequest) returns (.event.EventServerResopnse);</code>
   */
  public abstract void volunteerInteractionEvent(
      com.google.protobuf.RpcController controller,
      com.example.ex3_2_back.grpc.server.event.VolunteerInteractionEventRequest request,
      com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done);

  /**
   * <code>rpc StrangerDetectionEvent(.event.StrangerDetectionEventRequest) returns (.event.EventServerResopnse);</code>
   */
  public abstract void strangerDetectionEvent(
      com.google.protobuf.RpcController controller,
      com.example.ex3_2_back.grpc.server.event.StrangerDetectionEventRequest request,
      com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done);

  /**
   * <code>rpc FallDetectionEvent(.event.FallDetectionEventRequest) returns (.event.EventServerResopnse);</code>
   */
  public abstract void fallDetectionEvent(
      com.google.protobuf.RpcController controller,
      com.example.ex3_2_back.grpc.server.event.FallDetectionEventRequest request,
      com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done);

  /**
   * <code>rpc ForbiddenAreaInvasionDetectionEvent(.event.ForbiddenAreaInvasionDetectionEventRequest) returns (.event.EventServerResopnse);</code>
   */
  public abstract void forbiddenAreaInvasionDetectionEvent(
      com.google.protobuf.RpcController controller,
      com.example.ex3_2_back.grpc.server.event.ForbiddenAreaInvasionDetectionEventRequest request,
      com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.example.ex3_2_back.grpc.server.event.EventServiceProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.emotionDetectionEvent(controller, (com.example.ex3_2_back.grpc.server.event.EmotionDetectionEventRequest)request,
          com.google.protobuf.RpcUtil.<com.example.ex3_2_back.grpc.server.event.EventServerResopnse>specializeCallback(
            done));
        return;
      case 1:
        this.volunteerInteractionEvent(controller, (com.example.ex3_2_back.grpc.server.event.VolunteerInteractionEventRequest)request,
          com.google.protobuf.RpcUtil.<com.example.ex3_2_back.grpc.server.event.EventServerResopnse>specializeCallback(
            done));
        return;
      case 2:
        this.strangerDetectionEvent(controller, (com.example.ex3_2_back.grpc.server.event.StrangerDetectionEventRequest)request,
          com.google.protobuf.RpcUtil.<com.example.ex3_2_back.grpc.server.event.EventServerResopnse>specializeCallback(
            done));
        return;
      case 3:
        this.fallDetectionEvent(controller, (com.example.ex3_2_back.grpc.server.event.FallDetectionEventRequest)request,
          com.google.protobuf.RpcUtil.<com.example.ex3_2_back.grpc.server.event.EventServerResopnse>specializeCallback(
            done));
        return;
      case 4:
        this.forbiddenAreaInvasionDetectionEvent(controller, (com.example.ex3_2_back.grpc.server.event.ForbiddenAreaInvasionDetectionEventRequest)request,
          com.google.protobuf.RpcUtil.<com.example.ex3_2_back.grpc.server.event.EventServerResopnse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.ex3_2_back.grpc.server.event.EmotionDetectionEventRequest.getDefaultInstance();
      case 1:
        return com.example.ex3_2_back.grpc.server.event.VolunteerInteractionEventRequest.getDefaultInstance();
      case 2:
        return com.example.ex3_2_back.grpc.server.event.StrangerDetectionEventRequest.getDefaultInstance();
      case 3:
        return com.example.ex3_2_back.grpc.server.event.FallDetectionEventRequest.getDefaultInstance();
      case 4:
        return com.example.ex3_2_back.grpc.server.event.ForbiddenAreaInvasionDetectionEventRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance();
      case 1:
        return com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance();
      case 2:
        return com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance();
      case 3:
        return com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance();
      case 4:
        return com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.example.ex3_2_back.grpc.server.event.EventService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void emotionDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.EmotionDetectionEventRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.ex3_2_back.grpc.server.event.EventServerResopnse.class,
          com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance()));
    }

    public  void volunteerInteractionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.VolunteerInteractionEventRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.ex3_2_back.grpc.server.event.EventServerResopnse.class,
          com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance()));
    }

    public  void strangerDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.StrangerDetectionEventRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.ex3_2_back.grpc.server.event.EventServerResopnse.class,
          com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance()));
    }

    public  void fallDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.FallDetectionEventRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.ex3_2_back.grpc.server.event.EventServerResopnse.class,
          com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance()));
    }

    public  void forbiddenAreaInvasionDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.ForbiddenAreaInvasionDetectionEventRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.event.EventServerResopnse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(4),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.ex3_2_back.grpc.server.event.EventServerResopnse.class,
          com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.example.ex3_2_back.grpc.server.event.EventServerResopnse emotionDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.EmotionDetectionEventRequest request)
        throws com.google.protobuf.ServiceException;

    public com.example.ex3_2_back.grpc.server.event.EventServerResopnse volunteerInteractionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.VolunteerInteractionEventRequest request)
        throws com.google.protobuf.ServiceException;

    public com.example.ex3_2_back.grpc.server.event.EventServerResopnse strangerDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.StrangerDetectionEventRequest request)
        throws com.google.protobuf.ServiceException;

    public com.example.ex3_2_back.grpc.server.event.EventServerResopnse fallDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.FallDetectionEventRequest request)
        throws com.google.protobuf.ServiceException;

    public com.example.ex3_2_back.grpc.server.event.EventServerResopnse forbiddenAreaInvasionDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.ForbiddenAreaInvasionDetectionEventRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.example.ex3_2_back.grpc.server.event.EventServerResopnse emotionDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.EmotionDetectionEventRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.ex3_2_back.grpc.server.event.EventServerResopnse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance());
    }


    public com.example.ex3_2_back.grpc.server.event.EventServerResopnse volunteerInteractionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.VolunteerInteractionEventRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.ex3_2_back.grpc.server.event.EventServerResopnse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance());
    }


    public com.example.ex3_2_back.grpc.server.event.EventServerResopnse strangerDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.StrangerDetectionEventRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.ex3_2_back.grpc.server.event.EventServerResopnse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance());
    }


    public com.example.ex3_2_back.grpc.server.event.EventServerResopnse fallDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.FallDetectionEventRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.ex3_2_back.grpc.server.event.EventServerResopnse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance());
    }


    public com.example.ex3_2_back.grpc.server.event.EventServerResopnse forbiddenAreaInvasionDetectionEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.event.ForbiddenAreaInvasionDetectionEventRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.ex3_2_back.grpc.server.event.EventServerResopnse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(4),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.event.EventServerResopnse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:event.EventService)
}

