// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.example.ex3_2_back.grpc.server;

public final class EventServiceProto {
  private EventServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_EventServerResopnse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_EventServerResopnse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_EventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_EventRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\005event\"B\n\023EventServerResop" +
      "nse\022\017\n\007message\030\001 \001(\t\022\014\n\004code\030\002 \001(\005\022\014\n\004da" +
      "ta\030\003 \001(\t\"x\n\014EventRequest\022\021\n\teventType\030\001 " +
      "\001(\005\022\021\n\teventDate\030\002 \001(\t\022\025\n\reventLocation\030" +
      "\003 \001(\t\022\030\n\020eventDescription\030\004 \001(\t\022\021\n\telder" +
      "lyId\030\005 \001(\0052N\n\014EventService\022>\n\013CreateEven" +
      "t\022\023.event.EventRequest\032\032.event.EventServ" +
      "erResopnseB<\n\"com.example.ex3_2_back.grp" +
      "c.serverB\021EventServiceProtoP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_event_EventServerResopnse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_EventServerResopnse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_EventServerResopnse_descriptor,
        new java.lang.String[] { "Message", "Code", "Data", });
    internal_static_event_EventRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_event_EventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_EventRequest_descriptor,
        new java.lang.String[] { "EventType", "EventDate", "EventLocation", "EventDescription", "ElderlyId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
