// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.example.ex3_2_back.grpc.server;

public interface EventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event.EventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 eventType = 1;</code>
   * @return The eventType.
   */
  int getEventType();

  /**
   * <code>string eventDate = 2;</code>
   * @return The eventDate.
   */
  java.lang.String getEventDate();
  /**
   * <code>string eventDate = 2;</code>
   * @return The bytes for eventDate.
   */
  com.google.protobuf.ByteString
      getEventDateBytes();

  /**
   * <code>string eventLocation = 3;</code>
   * @return The eventLocation.
   */
  java.lang.String getEventLocation();
  /**
   * <code>string eventLocation = 3;</code>
   * @return The bytes for eventLocation.
   */
  com.google.protobuf.ByteString
      getEventLocationBytes();

  /**
   * <code>string eventDescription = 4;</code>
   * @return The eventDescription.
   */
  java.lang.String getEventDescription();
  /**
   * <code>string eventDescription = 4;</code>
   * @return The bytes for eventDescription.
   */
  com.google.protobuf.ByteString
      getEventDescriptionBytes();

  /**
   * <code>int32 elderlyId = 5;</code>
   * @return The elderlyId.
   */
  int getElderlyId();
}
