// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.example.ex3_2_back.grpc.server;

/**
 * Protobuf service {@code event.EventService}
 */
public  abstract class EventService
    implements com.google.protobuf.Service {
  protected EventService() {}

  public interface Interface {
    /**
     * <code>rpc CreateEvent(.event.EventRequest) returns (.event.EventServerResopnse);</code>
     */
    public abstract void createEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.EventRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.EventServerResopnse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new EventService() {
      @java.lang.Override
      public  void createEvent(
          com.google.protobuf.RpcController controller,
          com.example.ex3_2_back.grpc.server.EventRequest request,
          com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.EventServerResopnse> done) {
        impl.createEvent(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.createEvent(controller, (com.example.ex3_2_back.grpc.server.EventRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.ex3_2_back.grpc.server.EventRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.ex3_2_back.grpc.server.EventServerResopnse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc CreateEvent(.event.EventRequest) returns (.event.EventServerResopnse);</code>
   */
  public abstract void createEvent(
      com.google.protobuf.RpcController controller,
      com.example.ex3_2_back.grpc.server.EventRequest request,
      com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.EventServerResopnse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.example.ex3_2_back.grpc.server.EventServiceProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.createEvent(controller, (com.example.ex3_2_back.grpc.server.EventRequest)request,
          com.google.protobuf.RpcUtil.<com.example.ex3_2_back.grpc.server.EventServerResopnse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.ex3_2_back.grpc.server.EventRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.ex3_2_back.grpc.server.EventServerResopnse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.example.ex3_2_back.grpc.server.EventService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void createEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.EventRequest request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.EventServerResopnse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.EventServerResopnse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.ex3_2_back.grpc.server.EventServerResopnse.class,
          com.example.ex3_2_back.grpc.server.EventServerResopnse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.example.ex3_2_back.grpc.server.EventServerResopnse createEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.EventRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.example.ex3_2_back.grpc.server.EventServerResopnse createEvent(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.EventRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.ex3_2_back.grpc.server.EventServerResopnse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.EventServerResopnse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:event.EventService)
}

