// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.example.ex3_2_back.grpc.server.message;

/**
 * Protobuf service {@code message.Greeter}
 */
public  abstract class Greeter
    implements com.google.protobuf.Service {
  protected Greeter() {}

  public interface Interface {
    /**
     * <code>rpc Model1Request(.message.Model1RequestMessage) returns (.message.Model1ResponseMessage);</code>
     */
    public abstract void model1Request(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.message.Model1RequestMessage request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage> done);

    /**
     * <code>rpc Model2Request(.message.Model2RequestMessage) returns (.message.Model2ResponseMessage);</code>
     */
    public abstract void model2Request(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.message.Model2RequestMessage request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage> done);

    /**
     * <code>rpc Model3Request(.message.Model3RequestMessage) returns (.message.Model3ResponseMessage);</code>
     */
    public abstract void model3Request(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.message.Model3RequestMessage request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new Greeter() {
      @java.lang.Override
      public  void model1Request(
          com.google.protobuf.RpcController controller,
          com.example.ex3_2_back.grpc.server.message.Model1RequestMessage request,
          com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage> done) {
        impl.model1Request(controller, request, done);
      }

      @java.lang.Override
      public  void model2Request(
          com.google.protobuf.RpcController controller,
          com.example.ex3_2_back.grpc.server.message.Model2RequestMessage request,
          com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage> done) {
        impl.model2Request(controller, request, done);
      }

      @java.lang.Override
      public  void model3Request(
          com.google.protobuf.RpcController controller,
          com.example.ex3_2_back.grpc.server.message.Model3RequestMessage request,
          com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage> done) {
        impl.model3Request(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.model1Request(controller, (com.example.ex3_2_back.grpc.server.message.Model1RequestMessage)request);
          case 1:
            return impl.model2Request(controller, (com.example.ex3_2_back.grpc.server.message.Model2RequestMessage)request);
          case 2:
            return impl.model3Request(controller, (com.example.ex3_2_back.grpc.server.message.Model3RequestMessage)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.ex3_2_back.grpc.server.message.Model1RequestMessage.getDefaultInstance();
          case 1:
            return com.example.ex3_2_back.grpc.server.message.Model2RequestMessage.getDefaultInstance();
          case 2:
            return com.example.ex3_2_back.grpc.server.message.Model3RequestMessage.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage.getDefaultInstance();
          case 1:
            return com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage.getDefaultInstance();
          case 2:
            return com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc Model1Request(.message.Model1RequestMessage) returns (.message.Model1ResponseMessage);</code>
   */
  public abstract void model1Request(
      com.google.protobuf.RpcController controller,
      com.example.ex3_2_back.grpc.server.message.Model1RequestMessage request,
      com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage> done);

  /**
   * <code>rpc Model2Request(.message.Model2RequestMessage) returns (.message.Model2ResponseMessage);</code>
   */
  public abstract void model2Request(
      com.google.protobuf.RpcController controller,
      com.example.ex3_2_back.grpc.server.message.Model2RequestMessage request,
      com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage> done);

  /**
   * <code>rpc Model3Request(.message.Model3RequestMessage) returns (.message.Model3ResponseMessage);</code>
   */
  public abstract void model3Request(
      com.google.protobuf.RpcController controller,
      com.example.ex3_2_back.grpc.server.message.Model3RequestMessage request,
      com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.example.ex3_2_back.grpc.server.message.GreeterProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.model1Request(controller, (com.example.ex3_2_back.grpc.server.message.Model1RequestMessage)request,
          com.google.protobuf.RpcUtil.<com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage>specializeCallback(
            done));
        return;
      case 1:
        this.model2Request(controller, (com.example.ex3_2_back.grpc.server.message.Model2RequestMessage)request,
          com.google.protobuf.RpcUtil.<com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage>specializeCallback(
            done));
        return;
      case 2:
        this.model3Request(controller, (com.example.ex3_2_back.grpc.server.message.Model3RequestMessage)request,
          com.google.protobuf.RpcUtil.<com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.ex3_2_back.grpc.server.message.Model1RequestMessage.getDefaultInstance();
      case 1:
        return com.example.ex3_2_back.grpc.server.message.Model2RequestMessage.getDefaultInstance();
      case 2:
        return com.example.ex3_2_back.grpc.server.message.Model3RequestMessage.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage.getDefaultInstance();
      case 1:
        return com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage.getDefaultInstance();
      case 2:
        return com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.example.ex3_2_back.grpc.server.message.Greeter implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void model1Request(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.message.Model1RequestMessage request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage.class,
          com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage.getDefaultInstance()));
    }

    public  void model2Request(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.message.Model2RequestMessage request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage.class,
          com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage.getDefaultInstance()));
    }

    public  void model3Request(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.message.Model3RequestMessage request,
        com.google.protobuf.RpcCallback<com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage.class,
          com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage model1Request(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.message.Model1RequestMessage request)
        throws com.google.protobuf.ServiceException;

    public com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage model2Request(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.message.Model2RequestMessage request)
        throws com.google.protobuf.ServiceException;

    public com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage model3Request(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.message.Model3RequestMessage request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage model1Request(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.message.Model1RequestMessage request)
        throws com.google.protobuf.ServiceException {
      return (com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.message.Model1ResponseMessage.getDefaultInstance());
    }


    public com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage model2Request(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.message.Model2RequestMessage request)
        throws com.google.protobuf.ServiceException {
      return (com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.message.Model2ResponseMessage.getDefaultInstance());
    }


    public com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage model3Request(
        com.google.protobuf.RpcController controller,
        com.example.ex3_2_back.grpc.server.message.Model3RequestMessage request)
        throws com.google.protobuf.ServiceException {
      return (com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.example.ex3_2_back.grpc.server.message.Model3ResponseMessage.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:message.Greeter)
}

