// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.example.ex3_2_back.grpc.server.message;

public final class GreeterProto {
  private GreeterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Model1RequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Model1RequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Model1ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Model1ResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Model2RequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Model2RequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Model2ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Model2ResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Model3RequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Model3RequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Model3ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Model3ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\007message\"K\n\024Model1Reques" +
      "tMessage\022\020\n\010model_id\030\001 \001(\t\022\017\n\007user_id\030\002 " +
      "\001(\t\022\020\n\010username\030\003 \001(\t\"g\n\025Model1ResponseM" +
      "essage\022\014\n\004code\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\022\017\n\007use" +
      "r_id\030\003 \001(\t\022\020\n\010username\030\004 \001(\t\022\020\n\010model_id" +
      "\030\005 \001(\t\"T\n\024Model2RequestMessage\022\014\n\004code\030\001" +
      " \001(\t\022\013\n\003url\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\t\022\020\n\010mo" +
      "del_id\030\004 \001(\t\"U\n\025Model2ResponseMessage\022\014\n" +
      "\004code\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\022\017\n\007user_id\030\003 \001(" +
      "\t\022\020\n\010model_id\030\004 \001(\t\"C\n\024Model3RequestMess" +
      "age\022\014\n\004code\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\022\020\n\010model_" +
      "id\030\003 \001(\t\"D\n\025Model3ResponseMessage\022\014\n\004cod" +
      "e\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\022\020\n\010model_id\030\003 \001(\t2\377" +
      "\001\n\007Greeter\022P\n\rModel1Request\022\035.message.Mo" +
      "del1RequestMessage\032\036.message.Model1Respo" +
      "nseMessage\"\000\022P\n\rModel2Request\022\035.message." +
      "Model2RequestMessage\032\036.message.Model2Res" +
      "ponseMessage\"\000\022P\n\rModel3Request\022\035.messag" +
      "e.Model3RequestMessage\032\036.message.Model3R" +
      "esponseMessage\"\000B?\n*com.example.ex3_2_ba" +
      "ck.grpc.server.messageB\014GreeterProtoP\001\210\001" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_message_Model1RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_Model1RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Model1RequestMessage_descriptor,
        new java.lang.String[] { "ModelId", "UserId", "Username", });
    internal_static_message_Model1ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_Model1ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Model1ResponseMessage_descriptor,
        new java.lang.String[] { "Code", "Url", "UserId", "Username", "ModelId", });
    internal_static_message_Model2RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_Model2RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Model2RequestMessage_descriptor,
        new java.lang.String[] { "Code", "Url", "UserId", "ModelId", });
    internal_static_message_Model2ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_message_Model2ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Model2ResponseMessage_descriptor,
        new java.lang.String[] { "Code", "Url", "UserId", "ModelId", });
    internal_static_message_Model3RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_message_Model3RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Model3RequestMessage_descriptor,
        new java.lang.String[] { "Code", "Url", "ModelId", });
    internal_static_message_Model3ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_message_Model3ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Model3ResponseMessage_descriptor,
        new java.lang.String[] { "Code", "Url", "ModelId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
