// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.example.ex3_2_back.grpc.server.message;

public interface Model1RequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.Model1RequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string model_id = 1;</code>
   * @return The modelId.
   */
  java.lang.String getModelId();
  /**
   * <code>string model_id = 1;</code>
   * @return The bytes for modelId.
   */
  com.google.protobuf.ByteString
      getModelIdBytes();

  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
